# Generated by Django 4.2.5 on 2023-10-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contract_terms', models.CharField(max_length=100)),
                ('signing_bonus', models.CharField(max_length=100)),
                ('avg_salary', models.CharField(max_length=100)),
                ('total_gtd', models.CharField(max_length=100)),
            ],
        ),
    ]
